// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-4KQibT0a-bRCSl-USuKfogdKANViHig',
    appId: '1:101494572929:web:bc290b598891c7e0f00a80',
    messagingSenderId: '101494572929',
    projectId: 'retail-inventory-manager-2ad82',
    authDomain: 'retail-inventory-manager-2ad82.firebaseapp.com',
    storageBucket: 'retail-inventory-manager-2ad82.firebasestorage.app',
    measurementId: 'G-VZQ9951Z0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9IZ4fkc4M27pGvTnCmyWbpwGk0fFPgx8',
    appId: '1:101494572929:android:f69530832ab91ca7f00a80',
    messagingSenderId: '101494572929',
    projectId: 'retail-inventory-manager-2ad82',
    storageBucket: 'retail-inventory-manager-2ad82.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-4KQibT0a-bRCSl-USuKfogdKANViHig',
    appId: '1:101494572929:web:3bc6351cd53b4fedf00a80',
    messagingSenderId: '101494572929',
    projectId: 'retail-inventory-manager-2ad82',
    authDomain: 'retail-inventory-manager-2ad82.firebaseapp.com',
    storageBucket: 'retail-inventory-manager-2ad82.firebasestorage.app',
    measurementId: 'G-88N0ZW309M',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ZauNIiJGZXmYN3bYANXLjoDMiofIaC0',
    appId: '1:101494572929:ios:be8db80538b438a7f00a80',
    messagingSenderId: '101494572929',
    projectId: 'retail-inventory-manager-2ad82',
    storageBucket: 'retail-inventory-manager-2ad82.firebasestorage.app',
    iosBundleId: 'com.retail.inventorymanage',
  );
}
